### ISSUE TITLE
[Question] Alert controller and change detection

### ISSUE THREAD

**Issue by Yakoust** [szerner/ionic4-change-detection#1]
Hi,

I still experiment the issue you described here https://github.com/ionic-team/ionic/issues/15871
Is it still the case for you?

Damien

**Comment by szerner** [comment]
Hi Damien,

 

I just upgraded my github example to ionic 4.0.0-beta.15, tested it and the issue is there again. With beta.13 it works as expected.

So I filed a new issue on github (https://github.com/ionic-team/ionic/issues/16338), since the old one has been closed.

**Comment by Yakoust** [comment]
Closes with https://github.com/ionic-team/ionic/commit/b8dae5e5d58baa85be1287875631b7b83ceae85f
